// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** Neon (serverless) se suspend au repos : son réveil peut dépasser les 5 s
 *  par défaut de Prisma (P1001 au migrate deploy). On allonge le timeout. */
function withConnectTimeout(url: string | undefined): string | undefined {
  if (!url || url.includes("connect_timeout")) return url;
  return `${url}${url.includes("?") ? "&" : "?"}connect_timeout=20`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: withConnectTimeout(process.env["DATABASE_URL"]),
  },
});
