// Données partagées Pocket Drifterz — Saison 1 · Moteur Forgé
// Utilisé par la fiche carte dédiée et la recherche globale.
// rar: c=Commune, r=Rare Holo, u=Ultra Rare, l=Légendaire, g=Gold
// + unique, promotional, special, collaboration, signed

export const META = {
  c: { glyph: "◆", color: "#9BA3B2", label: "Commune", tilt: 3, holo: "0.3" },
  r: { glyph: "◈", color: "#4FA3FF", label: "Rare", tilt: 5, holo: "0.5" },
  u: { glyph: "✦", color: "#B05CFF", label: "Ultra Rare", tilt: 6, holo: "0.65" },
  l: { glyph: "❀", color: "#FF2E63", label: "Légendaire", tilt: 8, holo: "0.8" },
  g: { glyph: "✸", color: "#E8B23A", label: "Gold", tilt: 8, holo: "0.85" },
  unique: { glyph: "✪", color: "#6FE3D0", label: "Unique", tilt: 9, holo: "0.9" },
  promotional: { glyph: "★", color: "#FF6B9D", label: "Promotionnelle", tilt: 9, holo: "0.88" },
  special: { glyph: "◇", color: "#A78BFA", label: "Spécial", tilt: 9, holo: "0.88" },
  collaboration: { glyph: "✧", color: "#34D399", label: "Collaboration", tilt: 9, holo: "0.9" },
  signed: { glyph: "✒", color: "#F59E0B", label: "Signé", tilt: 9, holo: "0.92" },
};

export const COUNTRY = { JP: "JAPON", US: "USA", DE: "ALLEMAGNE" };

// num, name, rarity, img, val(€ cote), ch(puissance), kg(poids), country, desc
const RAW = [
  [
    0,
    "NISSAN LEOPARD F31 BOSOZOKU",
    "promotional",
    "00_NISSAN_LEOPARD_F31_SPECIALE.jpg",
    40,
    250,
    1450,
    "JP",
    "Nez allongé, échappements démesurés, peinture criarde : cette Leopard version bosozoku ne cherche pas la discrétion. Elle hurle plus qu'elle ne roule, et défile comme un drapeau rebelle sur l'asphalte japonais. Carte promo 1ère édition.",
  ],
  [
    1,
    "NISSAN SILVIA S13 MISSILE",
    "c",
    "01-NISSAN_S13_MISSILE.jpg",
    30,
    280,
    1200,
    "JP",
    "Réparée et remise sur piste environ 422 fois, c'est la voiture parfaite pour aller baptiser les portes des adversaires. Délabrée à l'extérieur mais armée d'un SR20DET qui chantonne.",
  ],
  [
    2,
    "NISSAN SILVIA PS13",
    "c",
    "02-Nissan_PS13.jpg",
    20,
    205,
    1250,
    "JP",
    "Avec sa silhouette tranchante, la PS13 incarne une époque où chaque ligne avait du caractère. Agile et nerveuse, elle est vite devenue une légende du drift underground.",
  ],
  [
    3,
    "NISSAN SILVIA S14",
    "c",
    "03-NISSAN_S14_B.jpg",
    20,
    220,
    1250,
    "JP",
    "La S14 pose les bases du châssis parfait : empattement long, propulsion, et un SR20 prêt à tout.",
  ],
  [
    4,
    "NISSAN SILVIA S15 SPEC-R",
    "c",
    "04-NISSAN_S15_SPECR.jpg",
    30,
    250,
    1240,
    "JP",
    "L'ultime évolution de la lignée Silvia : SR20DET de 250 ch, boîte 6 rapports et un châssis plus rigide. Agile et taillée pour le drift, c'est une légende.",
  ],
  [
    5,
    "NISSAN LAUREL C33",
    "c",
    "05-NISSAN_LAUREL_C33.jpg",
    20,
    205,
    1380,
    "JP",
    "La berline six-en-ligne préférée des drifteurs japonais. Discrète à l'arrêt, spectaculaire en travers.",
  ],
  [
    6,
    "MAZDA MX5 NA",
    "c",
    "06-MAZDA_MX5_cab.jpg",
    20,
    130,
    990,
    "JP",
    "La MX-5 NA, c'est aussi le drift en version décapotée. Légère, vive et joueuse, elle enchaîne les virages avec une facilité désarmante.",
  ],
  [
    7,
    "MAZDA MX5 NA",
    "c",
    "07-MAZDA_MX5_tunée.jpg",
    30,
    130,
    990,
    "JP",
    "Petite mais redoutable, elle se faufile sur les pistes de drift avec une agilité insolente. L'outsider préférée de la culture drift.",
  ],
  [
    8,
    "MAZDA MX5 NB",
    "c",
    "08-MAZDA_MX5_NB.jpg",
    20,
    146,
    1065,
    "JP",
    "La NB affine la recette Miata : plus rigide, plus précise, toujours aussi joueuse.",
  ],
  [
    9,
    "MAZDA MX5 NC",
    "c",
    "09-MAZDA_MX5_NC.jpg",
    20,
    170,
    1120,
    "JP",
    "Souvent oubliée entre ses grandes sœurs, la NC reste une vraie joueuse. L'esprit Miata avec un soupçon de modernité.",
  ],
  [
    10,
    "MAZDA RX7 FC",
    "c",
    "10-MAZDA_RX7_FC.jpg",
    20,
    200,
    1260,
    "JP",
    "Le rotatif première génération : léger, affûté, et des phares pop-up cultes.",
  ],
  [
    11,
    "TOYOTA CHASER JZX100",
    "c",
    "11-TOYOTA_CHASER_JZX100.jpg",
    30,
    280,
    1500,
    "JP",
    "La berline qui n'avait rien à faire là et qui a tout conquis. Propulsion, moteur 1JZ turbo, et une élégance brutale.",
  ],
  [
    12,
    "NISSAN 350Z",
    "c",
    "12-Nissan_350Z.jpg",
    20,
    280,
    1530,
    "JP",
    "Le V6 moderne de Nissan : couple généreux et châssis sain, une porte d'entrée vers le drift sérieux.",
  ],
  [
    13,
    "BMW E30 325I",
    "c",
    "13-BMW_E30_325i.jpg",
    20,
    170,
    1250,
    "DE",
    "Icône du drift en Europe, souvent marquée par ses passages sur circuit. Facile à réparer et abordable : une base idéale.",
  ],
  [
    14,
    "BMW SÉRIE 3 COMPACT E36",
    "c",
    "14-BMW_E36COMPACT.jpg",
    20,
    170,
    1250,
    "DE",
    "Une petite bombe sous-estimée. Agilité et moteur bavarois : une base parfaite pour le drift.",
  ],
  [
    15,
    "BMW E36 COMPACT MISSILE",
    "c",
    "15-BMW_E36COMPACT_MISSILE.jpg",
    20,
    170,
    1250,
    "DE",
    "Une Compact dépouillée, cabossée, et envoyée au combat. Zéro chichi, que de l'angle.",
  ],
  [
    16,
    "BMW E46 M3",
    "c",
    "16-BMW_E46_M3.jpg",
    20,
    343,
    1570,
    "DE",
    "Le S54 hurlant dans un châssis d'équilibriste : la précision allemande au service de la glisse.",
  ],
  [
    17,
    "BMW SÉRIE 1 E82",
    "c",
    "17-BMW_SERIE1_E82.jpg",
    20,
    306,
    1550,
    "DE",
    "Le drift en format compact : propulsion, châssis rigide, six cylindres réactif.",
  ],
  [
    18,
    "BMW SÉRIE 2 F22",
    "c",
    "18-BMW_S2_F22.jpg",
    20,
    184,
    1420,
    "DE",
    "Compacte, moderne, propulsion : la relève bavaroise prête à apprendre l'angle.",
  ],
  [
    19,
    "BMW M3 E92",
    "c",
    "19-BMW_M3_E92.jpg",
    30,
    420,
    1600,
    "DE",
    "Sous son capot, un V8 atmosphérique hurle ! La seule de sa lignée à oser ce moteur.",
  ],
  [
    20,
    "MERCEDES 560 SEC",
    "c",
    "20-MERCO_560.jpg",
    20,
    300,
    1880,
    "DE",
    "Le paquebot V8 de Stuttgart, converti au travers. Improbable, majestueux.",
  ],
  [
    21,
    "PORSCHE 944",
    "c",
    "21-PORSCHE_944.jpg",
    20,
    163,
    1180,
    "DE",
    "Transaxle, équilibre parfait, et un quatre cylindres vaillant : l'école de la finesse.",
  ],
  [
    22,
    "PORSCHE CAYMAN",
    "c",
    "22-PORSCHE_CAYMAN.jpg",
    30,
    420,
    1350,
    "DE",
    "Moteur central, propulsion, équilibre chirurgical : une base rare en drift, mais redoutable.",
  ],
  [
    23,
    "PONTIAC GTO",
    "c",
    "23-PONTIAC_GTO.jpg",
    20,
    400,
    1750,
    "US",
    "Sous ses airs de muscle car assagi, la GTO cache un V8 LS2 prêt à rugir. Lourde ? Oui. Sauvage ? Aussi.",
  ],
  [
    24,
    "FORD MUSTANG",
    "c",
    "24-FORD_MUSTANG.jpg",
    30,
    480,
    1650,
    "US",
    "Le muscle à l'état pur : long capot, gros V8, et une sonorité qui fait trembler l'asphalte.",
  ],
  [
    25,
    "CHEVROLET CAMARO SS",
    "c",
    "25-HEVROLET_CAMARO_SS_2000.jpg",
    30,
    430,
    1740,
    "US",
    "Le muscle car qui a mis un pied dans le futur sans oublier ses origines. V8 LS sous le capot.",
  ],
  [
    26,
    "CHEVROLET CAMARO SS",
    "c",
    "26-CHEVROLET_CAMARO_SS.jpg",
    30,
    500,
    1700,
    "US",
    "Le V8 qu'on voit souvent glisser dans des rodéos filmés au smartphone. Bruyante, sauvage.",
  ],
  [
    27,
    "CHEVROLET CORVETTE C5",
    "c",
    "27-CHEVROLET_CORVETTE_C5.jpg",
    40,
    350,
    1450,
    "US",
    "Plus qu'une voiture : une banque d'organes pour le drift. Son V8 LS1 a été greffé dans tout ce qui roule.",
  ],
  [
    28,
    "INFINITI G35 MISSILE",
    "c",
    "28-INFINITI_G35.jpg",
    20,
    280,
    1600,
    "US",
    "La cousine chic de la 350Z… sauf qu'en street culture, elle finit souvent entre de mauvaises mains.",
  ],
  [
    29,
    "INFINITI Q45",
    "c",
    "29-INFINITI_Q45.jpg",
    20,
    280,
    1800,
    "US",
    "Japonaise dans l'âme, américaine dans l'attitude. Un V8, de la propulsion, et une envie de drifter en costume.",
  ],
  [
    30,
    "INFINITI Q60",
    "c",
    "30-INFINITY_Q60.jpg",
    20,
    320,
    1750,
    "US",
    "Le coupé luxe qui cache un cœur de voyou. Twin-turbo et propulsion : tout est là.",
  ],
  [
    31,
    "NISSAN SKYLINE R31",
    "r",
    "31_NISSAN_Skyline_R31.jpg",
    20,
    320,
    1200,
    "JP",
    "Souvent oubliée entre la R30 et la R32, la R31 cache un vrai tempérament. Propulsion, lignes carrées, et un cœur RB.",
  ],
  [
    32,
    "NISSAN SKYLINE R32",
    "r",
    "32_NISSAN_SKYLINE_R32.jpg",
    30,
    215,
    1320,
    "JP",
    "Surnommée « Godzilla ». C'est la version GTS-T, propulsion, qui fait parler d'elle en drift. Une légende qui glisse avec autorité.",
  ],
  [
    33,
    "NISSAN SKYLINE R33",
    "r",
    "33_Nissan_R33_nismo.jpg",
    40,
    250,
    1450,
    "JP",
    "Souvent dans l'ombre de ses grandes sœurs, la R33 GTS-T est pourtant une vraie bête de drift. Un monstre discret.",
  ],
  [
    34,
    "NISSAN SKYLINE R34",
    "r",
    "34_NISSAN_SKYLINE-GTT.jpg",
    50,
    300,
    1400,
    "JP",
    "La R34 GTT est l'alter ego joueur de la GT-R. La fougue du RB25DET et l'agilité d'une pure propulsion.",
  ],
  [
    35,
    "NISSAN SILVIA S13 KOUKI",
    "r",
    "35_NISSAN_S13_KOUKI.jpg",
    30,
    205,
    1240,
    "JP",
    "La version la plus aboutie du modèle. Look affûté, feux arrière redessinés et SR20DET sous le capot.",
  ],
  [
    36,
    "NISSAN 300ZX Z32",
    "r",
    "36_Nissan-300zx-z32.jpg",
    30,
    283,
    1580,
    "JP",
    "Le drift version haute technologie des années 90. Ligne futuriste, double turbo, et des courbes intemporelles.",
  ],
  [
    37,
    "NISSAN 370 Z",
    "r",
    "37_NISSAN_370Z.jpg",
    30,
    350,
    1500,
    "JP",
    "Du drift clé en main. Châssis court, V6 nerveux, propulsion bien dosée. Adorée par les écoles de drift.",
  ],
  [
    38,
    "MAZDA RX7 FD",
    "r",
    "38_MAZDA_RXY_FD.jpg",
    30,
    280,
    1300,
    "JP",
    "L'élégance japonaise qui cache une vraie bête. Son rotatif bi-turbo pousse cette silhouette fluide à la limite.",
  ],
  [
    39,
    "TOYOTA SOARER",
    "r",
    "39_TOYOTA_SOARER_NEW.jpg",
    30,
    650,
    1450,
    "JP",
    "Le luxe qui a mal tourné. Longue, large, bardée de couple, elle surprend dès que l'arrière décroche.",
  ],
  [
    40,
    "TOYOTA COROLLA AE86 LEVIN",
    "r",
    "40_TOYOTA_COROLLA_LEVIN.jpg",
    20,
    130,
    940,
    "JP",
    "Une légende des montagnes. Icône suprême de la culture JDM avec sa sœur la Trueno.",
  ],
  [
    41,
    "HONDA S2000 PRÉPARÉE",
    "r",
    "41_HONDA_S2000.jpg",
    40,
    670,
    1100,
    "JP",
    "Jamais conçue pour le drift, mais elle y est déjà allée. VTEC haut perché, exigeante mais redoutable bien domptée.",
  ],
  [
    42,
    "TOYOTA SUPRA MK4",
    "r",
    "42_TOYOTA_SUPRA_MK4_rare.jpg",
    30,
    280,
    1300,
    "JP",
    "La légende devenue mythe. Avec son 2JZ-GTE suralimenté, elle a redéfini le mot « potentiel ». Elle est crainte !",
  ],
  [
    43,
    "BMW E30 TOURING",
    "r",
    "43_BMW_E30_TOURING.jpg",
    20,
    170,
    1200,
    "DE",
    "Sous ses airs de break vintage, la E30 Touring cache une âme rebelle. Une glisseuse old-school au mordant intact.",
  ],
  [
    44,
    "BMW E46 TOURING",
    "r",
    "44_BMW_E46_TOURING.jpg",
    20,
    300,
    1500,
    "DE",
    "À la base un break tranquille. Puis une bande de drifteurs est passée par là : intérieur vidé, arceau soudé.",
  ],
  [
    45,
    "BMW M5 E60",
    "r",
    "45_BMW-M5-E60.jpg",
    40,
    507,
    1830,
    "DE",
    "Ne vous fiez pas à ses airs de berline d'affaires. Un V10 qui hurle à 8 000 tours comme une bête échappée des paddocks.",
  ],
  [
    46,
    "BMW M4 COUPÉ",
    "r",
    "46_BMW_M4_COUPE.jpg",
    30,
    510,
    1800,
    "DE",
    "Précision allemande et caractère explosif. Six cylindres turbo aux roues arrière : une base redoutable.",
  ],
  [
    47,
    "MERCEDES-BENZ CLK 500",
    "r",
    "47_MERCO_CLK_500.jpg",
    40,
    750,
    1600,
    "DE",
    "Déguisée en bête de circuit, elle cache bien son jeu. Une drifteuse secrète sous une robe de course.",
  ],
  [
    48,
    "CHEVROLET CAMARO 1969",
    "r",
    "48_CHEVROLET_CAMARO_1969.jpg",
    30,
    500,
    1500,
    "US",
    "L'Amérique sur quatre roues. Lignes tendues, V8 grondant, regard méchant. Des courbes fumantes à l'ancienne.",
  ],
  [
    49,
    "DODGE VIPER SRT10",
    "r",
    "49_DODGE_VIPER_SRT10.jpg",
    30,
    500,
    1560,
    "US",
    "La puissance brute à l'américaine. Son V10 de 8,3 L transformé en machine de glisse improbable mais spectaculaire.",
  ],
  [
    50,
    "DODGE CHARGER SRT8",
    "r",
    "50_DODGE_CHARGER_SRT8.jpg",
    20,
    425,
    1900,
    "US",
    "Une berline… techniquement. Mais sous le capot, un HEMI V8 prêt à faire fondre l'asphalte.",
  ],
  [
    51,
    "NISSAN SILVIA S12",
    "u",
    "51_NISSAN_SILVIA_S12.jpg",
    30,
    300,
    1200,
    "JP",
    "La base de drift oubliée des années 80. Propulsion, turbo, look tranchant. Rare, mais pleine de caractère.",
  ],
  [
    52,
    "NISSAN S14 KOUKI",
    "u",
    "52_Nissan_S14A_preparee.jpg",
    40,
    300,
    1150,
    "JP",
    "Cette S14 orange a marqué son temps ! Présente dans les premières compétitions japonaises.",
  ],
  [
    53,
    "NISSAN S14 ZENKI",
    "u",
    "53_Nissan_S14_ZENKI.jpg",
    40,
    300,
    1150,
    "JP",
    "Au Japon, on raconte qu'une S14 Zenki couleur lila apparaissait à la tombée de la nuit, près de Gunma.",
  ],
  [
    54,
    "NISSAN SILVIA S15 ULTIME",
    "u",
    "54_NISSAN_S15_ICONIQUE.jpg",
    60,
    450,
    1200,
    "JP",
    "Cette S15 a marqué une génération entière de fans de drift. Créée par un maître de la discipline.",
  ],
  [
    55,
    "NISSAN SILVIA S15 ULTIME",
    "u",
    "55_NISSAN_S15_GENKI.jpg",
    60,
    480,
    1200,
    "JP",
    "Avec sa décoration et ses jantes uniques en leur genre, cette Silvia s'est inscrite dans l'histoire.",
  ],
  [
    56,
    "NISSAN SKYLINE R32 FANTÔME",
    "u",
    "56_NISSAN_SKYLINE_R32_fantôme.jpg",
    40,
    0,
    0,
    "JP",
    "La nuit, dans les touge, on l'entend avant de la voir. Une Skyline R32 noire qui disparaît sans laisser de trace.",
  ],
  [
    57,
    "NISSAN SKYLINE GTR R35",
    "u",
    "57_NISSAN_SKYLINE_R35.jpg",
    60,
    1000,
    1500,
    "JP",
    "Godzilla n'est pas née pour drifter. Mais certains ont osé : en propulsion, la R35 devient un monstre encore plus sauvage.",
  ],
  [
    58,
    "MAZDA RX7 FD PRÉPARÉE",
    "u",
    "58_MAZDA_RX7_PREPAREE.jpg",
    40,
    450,
    1200,
    "JP",
    "Une œuvre d'ingénierie japonaise. Rotatif bi-turbo, châssis taillé pour l'agilité : une icône intemporelle du JDM.",
  ],
  [
    59,
    "TOYOTA SUPRA MK4 SECRÈTE",
    "u",
    "59_TOYOTA_SUPRA_MK4_SECRET.jpg",
    50,
    1200,
    1250,
    "JP",
    "Cette Supra dorée, préparée par un maître du tuning, est devenue une légende. Plus de 1 000 chevaux, une ombre dorée.",
  ],
  [
    60,
    "SUBARU IMPREZA WRX STI",
    "u",
    "60_SUBARU_WRX.jpg",
    60,
    400,
    1270,
    "JP",
    "Cette Impreza STI n'est pas née pour le drift… mais elle l'a conquis. Propulsion convertie, livrée flamboyante.",
  ],
  [
    61,
    "SUBARU BRZ",
    "u",
    "61_SUBARU-BRZ.jpg",
    40,
    750,
    1100,
    "JP",
    "Partout en compétition : châssis affûté, poids contenu, propulsion réactive. Une base féroce, née pour l'attaque.",
  ],
  [
    62,
    "DAIHATSU KEI CAR",
    "u",
    "62_DAIHATSU_KEICAR_PRINTI.jpg",
    20,
    90,
    800,
    "JP",
    "« Tiens, j'entends des crissements de pneus… Ce doit être mon livreur ! » Une propulsion capable de monter les montagnes en travers.",
  ],
  [
    63,
    "BMW E36",
    "u",
    "63_BMW_E36_PREP.jpg",
    40,
    350,
    1460,
    "DE",
    "Une valeur sûre du drift. Châssis équilibré, propulsion fiable : le combo parfait pour progresser sur piste.",
  ],
  [
    64,
    "PORSCHE 911 RWB",
    "u",
    "64_PORSCHE_911_RWB.jpg",
    60,
    350,
    1350,
    "DE",
    "La fusion entre art et chaos mécanique. Élargie à la main, vissée à même la tôle, elle ne suit aucune règle.",
  ],
  [
    65,
    "BMW E36",
    "u",
    "65_BMW_E36_prepare.jpg",
    40,
    330,
    1460,
    "DE",
    "On ne sait pas vraiment d'où elle vient. Certains parlent d'une ancienne voiture de course échappée d'un paddock oublié.",
  ],
  [
    66,
    "MERCEDES-BENZ 190E EVO II DTM",
    "u",
    "66_MERCEDES_DTM_EVOII.jpg",
    50,
    235,
    1340,
    "DE",
    "Une 190E Evo II, sortie des grandes heures du DTM, qui débarque dans l'arène du drift avec une énergie d'un autre temps.",
  ],
  [
    67,
    "DODGE CHARGER R/T 1969",
    "u",
    "67_DODGE_CHARGER_1969.jpg",
    60,
    1200,
    1800,
    "US",
    "Du métal pur, tendu par un V8 qui gronde comme un orage. Lourde, sauvage, indomptable… sauf entre les mains d'un certain Dominique.",
  ],
  [
    68,
    "NISSAN 200SX S13 DU CRÉATEUR",
    "l",
    "68_NISSAN_S13_LIGHTON.jpg",
    30,
    200,
    1170,
    "JP",
    "Cette Nissan S13 est celle de Lighton, le créateur de ce jeu. Ses cicatrices viennent des battles perdues contre les dos-d'âne.",
  ],
  [
    69,
    "NISSAN 200SX S13 DU CRÉATEUR",
    "l",
    "69_NISSAN_S13_LIGHTON_2.jpg",
    30,
    200,
    1170,
    "JP",
    "La S13 du créateur, sous la pluie. Elle émet des grincements inconnus, mais le SR chante toujours.",
  ],
  [
    70,
    "NISSAN SILVIA PS13 DE MIKE",
    "l",
    "70_Nissan_PS13_Mike.jpg",
    60,
    550,
    1150,
    "JP",
    "La PS13 du pilote Mike Kauffmann, première collaboration artistique de Lighton. RB25 rugissant, un style flamboyant.",
  ],
  [
    71,
    "NISSAN SKYLINE R33 MIDNIGHT",
    "l",
    "71_NISSAN_R33_MIDNIGHT.jpg",
    40,
    215,
    1320,
    "JP",
    "Drapée dans son mythique Midnight Purple, cette Skyline R33 semble sortir d'un rêve nocturne. En glisse, elle hypnotise.",
  ],
  [
    72,
    "TOYOTA CHASER JZX MYSTIQUE",
    "l",
    "72_TOYOTA_JZX_KLUTCHVISUAL.jpg",
    40,
    850,
    1300,
    "JP",
    "Cette Chaser signée Klutch Visuals ne fait pas que drifter, elle capture. Chaque run laisse une trace, sur l'asphalte et la pellicule.",
  ],
  [
    73,
    "BMW SÉRIE 7 E32 DU PADRÉ",
    "l",
    "73_BMW_SERIE7_E32.jpg",
    40,
    200,
    1700,
    "DE",
    "Cette Série 7 est à l'origine de la passion automobile de Lighton. Le son du six-en-ligne le berçait sur le chemin de l'école.",
  ],
  [
    74,
    "DMC DELOREAN D'ALEXANDRE",
    "l",
    "74_DMC_DELOREAN.jpg",
    60,
    550,
    1280,
    "US",
    "Icône de la pop culture revue par Alexandre Claudin. Moteur de Corvette à l'avant, châssis tubulaire : un ovni du drift.",
  ],
  [
    75,
    "HONDA NSX TYPE-R NA1",
    "g",
    "75_HONDA_NSX_NA1.jpg",
    70,
    280,
    1230,
    "JP",
    "La noblesse japonaise sur quatre roues. Conçue avec l'aide d'Ayrton Senna. Sa rareté renforce son aura légendaire.",
  ],
  [
    76,
    "TOYOTA COROLLA AE86 TRUENO",
    "g",
    "76_TOYOTA_COROLLA_TRUENO.jpg",
    100,
    130,
    940,
    "JP",
    "L'emblème du drift ! Connue dans le monde entier grâce à un manga à succès, c'est la voiture avec laquelle tout a commencé.",
  ],
  [
    77,
    "NISSAN SKYLINE R34 TITANESQUE",
    "promotional",
    "77_NISSAN_R34_TITAN.jpg",
    40,
    1600,
    1250,
    "JP",
    "Entièrement façonnée en carbone, elle s'évapore dans les virages de Tokyo comme une ombre.",
  ],
  [
    78,
    "TOYOTA COROLLA AE86 LEVIN POCKET DRIFTER",
    "unique",
    "78_TOYOTA_COROLLA_AE86_LEVIN_POCKET_DRIFTER.jpg",
    100,
    280,
    940,
    "JP",
    "Édition artistique Pocket Drifter — la légende des montagnes repensée en full drift. Tout en travers !",
  ],
  [
    79,
    "MAZDA SAVANNA RX-7 FB",
    "unique",
    "79_MAZDA_SAVANNA_RX7_FB_UNIQUE.jpg",
    100,
    350,
    1050,
    "JP",
    "La FB en finition or Moteur Forge — rotatif de légende, silhouette Savanna, unique 01/01.",
  ],
];

export const CARDS = RAW.map((r) => ({
  num: r[0],
  name: r[1],
  r: r[2],
  img: r[3],
  val: r[4],
  ch: r[5],
  kg: r[6],
  co: r[7],
  d: r[8],
}));

/**
 * Versions optionnelles par numéro de carte (en plus de Standard).
 * unique · promotionnelle · spécial · collaboration · signé
 */
export const CARD_EXTRA_VERSIONS = {
  0: ["promotional", "special", "signed"],
  68: ["special"],
  70: ["collaboration"],
  72: ["collaboration", "signed"],
  74: ["collaboration"],
  78: ["unique"],
  79: ["unique"],
};

/** Libellé d'édition catalogue par défaut (Saison 1). */
export const DEFAULT_S01_EDITION_LABEL = "1ère édition";

/**
 * Surcharge d'édition par numéro de carte (null = illimitée).
 * Absent = DEFAULT_S01_EDITION_LABEL pour toute la saison.
 */
export const CARD_EDITION_LABELS = {
  78: "Pocket Drifter Edition 2023",
  79: "Moteur Forge édition 2024",
};
