-- Élargit la liste des transporteurs proposés au vendeur pour le suivi du colis.
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'SHOP2SHOP';
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'RELAIS_COLIS';
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'UPS';
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'DHL';
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'DPD';
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'GLS';
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'FEDEX';
ALTER TYPE "Carrier" ADD VALUE IF NOT EXISTS 'TNT';
